# This is a basic workflow to help you get started with Actions
name: publicacion-db

# Controls when the action will run.
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'zulu'
          cache: 'maven'
      - name: Run extraction
        run: mvn -B clean compile exec:java -D"exec.mainClass"="op.elecciones.AppDetalle"

      - uses: actions/setup-python@v1
      - name: publishes to datasette
        uses: BSFishy/pip-action@v1
        with:
          packages: |
            datasette
            sqlite-utils
      - name: csv-to-db
        run: |
            cat resultados-filtrados.ndjson  | sqlite-utils insert elecciones.db candidatos_detalle --nl --flatten --truncate --alter -
            cat resultados-filtrados.ndjson  | sqlite-utils insert elecciones.db candidatos_detalle_v2 --nl  --truncate --alter -

            cat resultados-filtrados-lima.ndjson  | sqlite-utils insert elecciones.db candidatos_detalle --nl --flatten --alter -
            cat resultados-filtrados-lima.ndjson  | sqlite-utils insert elecciones.db candidatos_detalle_v2 --nl  --alter -

      - name: Install vercel plugin
        run: |
          datasette install datasette-publish-vercel
      - name: Deploy Datasette using Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |-
          datasette publish vercel elecciones.db \
            --token $VERCEL_TOKEN \
            --no-prod \
            --project elecciones-regionales-2022 \
            --install datasette-vega \
            --install datasette-export-notebook \
            --install datasette-copyable \
            --install datasette-block-robots \
            --install datasette-pretty-json